name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: OSSRH Maven central 저장소 배포
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: ./gradlew publish