name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check deploy condition
        id: check_condition
        run: |
          if git branch --contains ${{ github.ref_name }} | grep -q "master\|main"; then
            echo "on_master=true" >> $GITHUB_OUTPUT
          else
            echo "on_master=false" >> $GITHUB_OUTPUT
            echo "Tag is not on master branch. Skipping deployment."
            exit 1
          fi
      - name: Get version from tag
        if: steps.check_condition.outputs.on_master == 'true'
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.ASCII_ARMORED_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: List keys
        run: gpg -K

      - name: OSSRH Maven central 저장소 배포
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publish