name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Singing GPG Key
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
          GPG_KEY_RING_FILE: ${{ secrets.GPG_KEY_RING_FILE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          echo ${{ secrets.OSSRH_USERNAME }}
          ./gradlew sign -Psigning.keyId=$GPG_KEY_ID -Psigning.password=$GPG_KEY_PASSWORD -Psigning.secretKeyRingFile=$GPG_KEY_RING_FILE

      - name: Publish artifacts to OSSRH Repository
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
          GPG_KEY_RING_FILE: ${{ secrets.GPG_KEY_RING_FILE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}