name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle Wrapper 유효성 검증
        uses: gradle/wrapper-validation-action@v1

      - name: GPG Key 가져오기
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY_ID }}
          passphrase: ${{ secrets.GPG_KEY_PASSWORD }}
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}

      - name: GPG Key 조회
        run: gpg --list-keys

      - name: 서명 파일 생성
        run: |
          export $SIGNING_KEY_FILE=$PWD/signing.pgp
          echo "signing key file path is $SIGNING_KEY_FILE"
          gpg --export-secret-keys ${{ secrets.GPG_FINGERPRINT_SHORT }} > $SIGNING_KEY_FILE
      - name: Gradle 서명
        run: |
          ./gradlew sign \
            -Psigning.keyId= ${{ secrets.GPG_FINGERPRINT_SHORT }} \
            -Psigning.password= ${{ secrets.GPG_KEY_PASSWORD }} \
            -Psigning.secretKeyRingFile=$SIGNING_KEY_FILE \
            -ossrhUsername=$OSSRH_USERNAME \
            -ossrhPassword=$OSSRH_PASSWORD

      - name: OSSRH Maven central 저장소 배포
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}