name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      singing.keyId: ${{ secrets.GPG_KEY_ID }}
      signing.password: ${{ secrets.GPG_KEY_PASSWORD }}
      signing.secretKeyRingFile: ${{ secrets.GPG_KEY_RING_FILE }}
      ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
      ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Signing gpg key
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: sign

      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
