name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check deploy condition
        id: check_condition
        run: |
          # 현재 HEAD에 태그가 있는지 확인
          TAG_NAME=$(git describe --exact-match --tags HEAD 2>/dev/null || echo "")
          
          if [[ $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "has_version_tag=true" >> $GITHUB_OUTPUT
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "Found version tag: $TAG_NAME"
          else
            echo "has_version_tag=false" >> $GITHUB_OUTPUT
            echo "tag_name=" >> $GITHUB_OUTPUT
            echo "No version tag found on current commit"
          fi

      - name: Get version from tag
        if: steps.check_condition.outputs.has_version_tag  == 'true'
        id: get_version
        run: |
          TAG_NAME="${{ steps.check_condition.outputs.tag_name }}"
          VERSION=${TAG_NAME#v}  # v 접두사 제거
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION from tag: $TAG_NAME"

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: OSSRH Maven central 저장소 배포
        if: steps.check_condition.outputs.has_version_tag == 'true'  # 조건 추가
        run: |
          TAG_NAME="${{ steps.check_condition.outputs.tag_name }}"
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Artifact version: $VERSION (from tag: $TAG_NAME)"
          ./gradlew jreleaserFullRelease -Pversion=$VERSION