name: publish-to-repository
run-name: Publish artifacts to repository
on:
  push:
    branches:
      - master
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          cache: gradle


      - name: Check deploy condition And Setting Version
        id: check_condition
        run: |
          # 현재 HEAD에 태그가 있는지 확인
          TAG_NAME=$(git describe --exact-match --tags HEAD 2>/dev/null || echo "")
          VERSION=${TAG_NAME#v}
          echo "Artifact version: $VERSION"
          if [[ -n $VERSION ]]; then
            echo "has_version_tag=true" >> $GITHUB_OUTPUT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release to Maven central 저장소 배포
        if: steps.check_condition.outputs.has_version_tag == 'true'  # 조건 추가
        env:
          SONATYPE_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        run: |
          export GPG_TTY=$(tty)
          VERSION="${{ steps.check_condition.outputs.version }}"
          ./gradlew jreleaserFullRelease -PVersion=$VERSION