name: publish-to-repository
run-name: Publish artifacts to repository
on:
    push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish-artifact-to-repository:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check deploy condition
        id: check_condition
        run: |
          if git describe --exact-match --tags HEAD 2>/dev/null | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+'; then
            echo "has_version_tag=true" >> $GITHUB_OUTPUT
          else
            echo "has_version_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Get version from tag
        if: steps.check_condition.outputs.has_version_tag  == 'true'
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Permission for gradlew with chmod
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: OSSRH Maven central 저장소 배포
        if: steps.check_condition.outputs.has_version_tag == 'true'  # 조건 추가
        run: ./gradlew jreleaserFullRelease